### ISSUE TITLE
Build and push a new release

### ISSUE THREAD

**Issue by Pyo25** [peterberkenbosch/sendcloud#8]
Hello,

The latest release (v1.0.0) was published on 7 Feb 2015.
Since then a few improvements were added to the lib, that would be really great to bump the minor and publish a v1.1.0 so that we can install the latest lib via Rubygems.

The workaround is to link the repo directly in the Gemfile:
```
gem 'sendcloud-ruby', :git => 'https://github.com/pero-ict-solutions/sendcloud.git'
```

Thanks you !

cc @peterberkenbosch @artyomlagun @fatboypunk

**Comment by peterberkenbosch** [comment]
I just pushed a new release to rubygems @Pyo25. Thanks for your patience!
